name: gemstone_fyp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  modal_progress_hud_nsn: ^0.5.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  email_validator: ^3.0.0
  google_sign_in: ^6.3.0
  http: ^1.3.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true


